### ISSUE TITLE
Handle Observable unsubscription

### ISSUE THREAD

**Issue by FranciscoE-Hudl** [pucamafra/RxNotification#2]
None of the Subscribers checks if subscription.isUnsubscribed() before forwarding the results to it, breaking the Observable contract. There is also no logic for cleaning up after cancellation.

**Comment by pucamafra** [comment]
Thank you for the tips. Problem solved

**Comment by FranciscoE-Hudl** [comment]
I made some comments on the commit because it's still not correct. If you're more comfortable with it, consider using other constructors instead of create(), like fromCallable(). The thread change can be done using subscribeOn().

**Comment by pucamafra** [comment]
What do you suggest, use fromCallable() or fix that old way where you commented?
and about performance, which one is better?

**Comment by FranciscoE-Hudl** [comment]
My general advice is that if you find the create() requirements too cumbersome, go for fromCallable(). It adds try/catch and respects unsubscription for you, and you only have to write your business logic code.
